### ISSUE TITLE
Set up user model

### ISSUE THREAD

**Issue by akanshmurthy** [health20sf/website#3]
We want users to have a name, email, and password digest. Users should also have their own profile page (where they can see basic things like what events they've gone to and which events they're registered for).

**Comment by jgerardsimcock** [comment]
Do you think we should add an organization/role attribute?

**Comment by jgerardsimcock** [comment]
Adding an organization/role attribute

**Comment by akanshmurthy** [comment]
To clarify, is this to categorize users? Can they enter whatever they want or will it have only a few possible options (like student, working professional, venture capitalist, etc.)?

**Comment by jgerardsimcock** [comment]
We'd limit the options and it would do a dropdown to show them the list. Just a thought. I am thinking about ways of identifying founders, funders, devs, bizdevs, etc. Maybe not important or maybe we can set this up on profile page details.

**Comment by akanshmurthy** [comment]
Ok, sounds good. Not crucial yet but it's a good anticipation.

**Comment by jgerardsimcock** [comment]
Created user model, and wrote tests for it with unit:test. Merged feature branch with master. You said you are going to use react for the view layer, right?

**Comment by akanshmurthy** [comment]
Yep. But, for the initial portions, I think we can get away with static pages. In fact, I think we can build out all the functionality with static pages and then refactor into React since each page could just be broken into various components.
